In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# Import required packages
import pandas as pd


In [ ]:
# Read the data
data = pd.read_excel('/content/drive/MyDrive/dataset72ann.xlsx')
data.head()

caste   rank gender branch
0      0  15733      m    cse
1      0  13808      f    cse
2      1  36314      m    cse
3      1  42674      f    cse
4      2  23781      m    cse

In [ ]:
data.describe()

caste          rank
count  71.000000     71.000000
mean    3.535211  57221.816901
std     2.413243  21713.438531
min     0.000000  13808.000000
25%     1.000000  35580.000000
50%     4.000000  64780.000000
75%     6.000000  74757.500000
max     7.000000  94518.000000

In [ ]:
# Convert gender into numeric data
gender = data.gender.unique()
data['gender'].replace(gender, range(len(gender)), inplace=True)
print(gender)
data.head()
# m = 0
# f = 1

['m' 'f']


caste   rank  gender branch
0      0  15733       0    cse
1      0  13808       1    cse
2      1  36314       0    cse
3      1  42674       1    cse
4      2  23781       0    cse

In [ ]:
# Proceed for training ANN


# Apply dummy coding on label (branch)
dummies = pd.get_dummies(data.branch)
data = pd.concat([data, dummies], axis = 1)
data.drop(['branch'], axis = 1, inplace = True)

data.head()

caste   rank  gender  ce  cse  ece  eee  me
0      0  15733       0   0    1    0    0   0
1      0  13808       1   0    1    0    0   0
2      1  36314       0   0    1    0    0   0
3      1  42674       1   0    1    0    0   0
4      2  23781       0   0    1    0    0   0

In [ ]:
# Split features and label
x = data.drop(['ce', 'cse', 'ece', 'eee', 'me'], axis=1)
y = data[['ce', 'cse', 'ece', 'eee', 'me']].to_numpy()

In [ ]:
x

caste   rank  gender
0       0  15733       0
1       0  13808       1
2       1  36314       0
3       1  42674       1
4       2  23781       0
..    ...    ...     ...
66      5  56372       0
67      6  86143       0
68      6  94518       1
69      7  82697       0
70      7  70741       1

[71 rows x 3 columns]

In [ ]:
from sklearn.preprocessing import MinMaxScaler
ms=MinMaxScaler()
x=ms.fit_transform(x)
print(x)

[[0.         0.02385082 0.        ]
 [0.         0.         1.        ]
 [0.14285714 0.2788502  0.        ]
 [0.14285714 0.35765085 1.        ]
 [0.28571429 0.12356585 0.        ]
 [0.28571429 0.16551852 1.        ]
 [0.42857143 0.61298476 0.        ]
 [0.42857143 0.16546896 1.        ]
 [0.57142857 0.11742039 0.        ]
 [0.57142857 0.11294759 1.        ]
 [0.71428571 0.22116219 0.        ]
 [0.71428571 0.27229587 1.        ]
 [0.85714286 0.33206542 0.        ]
 [0.85714286 0.48884897 1.        ]
 [1.         0.24497584 0.        ]
 [1.         0.37752447 1.        ]
 [0.         0.10019824 0.        ]
 [0.         0.12543675 1.        ]
 [0.14285714 0.67196134 0.        ]
 [0.14285714 0.46456449 1.        ]
 [0.28571429 0.30546401 0.        ]
 [0.28571429 0.26721596 1.        ]
 [0.57142857 0.25689506 0.        ]
 [0.57142857 0.26499814 1.        ]
 [0.71428571 0.66249535 0.        ]
 [0.71428571 0.50579854 1.        ]
 [0.85714286 0.74899021 0.        ]
 [0.85714286 0.82779086 1.  

In [ ]:
# Split data for training and testing
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=101)


In [ ]:
ytrain

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 1,

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

# Initialization of ANN model
model=Sequential()
model.add(Dense(5,activation='tanh', input_shape=(3,)))
model.add(Dense(5,activation='tanh'))
#model.add(Dense(70,activation='swish'))
model.add(Dense(5,activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_23 (Dense)            (None, 5)                 20        
                                                                 
 dense_24 (Dense)            (None, 5)                 30        
                                                                 
 dense_25 (Dense)            (None, 5)                 30        
                                                                 
Total params: 80
Trainable params: 80
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# Training the model
history = model.fit(xtrain, ytrain, batch_size=1, epochs=1000, verbose=1)

Epoch 1/1000
56/56 [==============================] - 0s 1ms/step - loss: 1.5832 - accuracy: 0.2321
Epoch 2/1000
56/56 [==============================] - 0s 2ms/step - loss: 1.5660 - accuracy: 0.2500
Epoch 3/1000
56/56 [==============================] - 0s 1ms/step - loss: 1.5548 - accuracy: 0.2679
Epoch 4/1000
56/56 [==============================] - 0s 2ms/step - loss: 1.5482 - accuracy: 0.3214
Epoch 5/1000
56/56 [==============================] - 0s 2ms/step - loss: 1.5422 - accuracy: 0.2679
Epoch 6/1000
56/56 [==============================] - 0s 2ms/step - loss: 1.5323 - accuracy: 0.3393
Epoch 7/1000
56/56 [==============================] - 0s 2ms/step - loss: 1.5246 - accuracy: 0.3393
Epoch 8/1000
56/56 [==============================] - 0s 2ms/step - loss: 1.5188 - accuracy: 0.3393
Epoch 9/1000
56/56 [==============================] - 0s 1ms/step - loss: 1.5130 - accuracy: 0.3393
Epoch 10/1000
56/56 [==============================] - 0s 1ms/step - loss: 1.5041 - accuracy: 0.3214

In [ ]:
history1 = model.fit(xtest, ytest, batch_size=1, epochs=1000, verbose=1)

Epoch 1/1000
15/15 [==============================] - 0s 2ms/step - loss: 16.3526 - accuracy: 0.0667
Epoch 2/1000
15/15 [==============================] - 0s 2ms/step - loss: 8.8895 - accuracy: 0.1333
Epoch 3/1000
15/15 [==============================] - 0s 2ms/step - loss: 4.8142 - accuracy: 0.3333
Epoch 4/1000
15/15 [==============================] - 0s 2ms/step - loss: 2.8088 - accuracy: 0.6000
Epoch 5/1000
15/15 [==============================] - 0s 2ms/step - loss: 2.0133 - accuracy: 0.8000
Epoch 6/1000
15/15 [==============================] - 0s 2ms/step - loss: 1.3552 - accuracy: 0.8667
Epoch 7/1000
15/15 [==============================] - 0s 2ms/step - loss: 1.0079 - accuracy: 0.8667
Epoch 8/1000
15/15 [==============================] - 0s 2ms/step - loss: 0.8399 - accuracy: 0.9333
Epoch 9/1000
15/15 [==============================] - 0s 3ms/step - loss: 0.6208 - accuracy: 0.9333
Epoch 10/1000
15/15 [==============================] - 0s 2ms/step - loss: 0.4948 - accuracy: 0.933

In [ ]:
history.history['accuracy']

[0.1071428582072258,
 0.2321428507566452,
 0.2321428507566452,
 0.3214285671710968,
 0.375,
 0.4285714328289032,
 0.375,
 0.4107142984867096,
 0.4285714328289032,
 0.4464285671710968,
 0.4107142984867096,
 0.4642857015132904,
 0.4642857015132904,
 0.4107142984867096,
 0.4464285671710968,
 0.4464285671710968,
 0.4642857015132904,
 0.5535714030265808,
 0.4642857015132904,
 0.4642857015132904,
 0.4464285671710968,
 0.4464285671710968,
 0.4285714328289032,
 0.5357142686843872,
 0.4107142984867096,
 0.4642857015132904,
 0.5357142686843872,
 0.4642857015132904,
 0.5178571343421936,
 0.4464285671710968,
 0.5178571343421936,
 0.4642857015132904,
 0.5535714030265808,
 0.5178571343421936,
 0.4285714328289032,
 0.4642857015132904,
 0.5178571343421936,
 0.4642857015132904,
 0.4285714328289032,
 0.5,
 0.4464285671710968,
 0.4642857015132904,
 0.5,
 0.5,
 0.4821428656578064,
 0.5535714030265808,
 0.5178571343421936,
 0.4464285671710968,
 0.4821428656578064,
 0.4821428656578064,
 0.5178571343421936,


In [ ]:
model.predict(xtrain[:5])

array([[1.3407118e-12, 9.7808194e-01, 2.1918001e-02, 2.9154103e-08,
        3.7112398e-09],
       [3.5673847e-06, 3.1808386e-06, 9.3885022e-01, 5.0917201e-02,
        1.0225840e-02],
       [2.7983556e-26, 1.4512826e-08, 1.0000000e+00, 3.7528771e-27,
        0.0000000e+00],
       [4.0192500e-08, 4.7293591e-09, 9.9998796e-01, 1.1825463e-05,
        2.6955124e-07],
       [4.3884260e-10, 4.8555106e-01, 5.1444888e-01, 4.2433396e-12,
        2.4496147e-13]], dtype=float32)

In [ ]:
xtrain[:5]

array([[0.28571429, 0.26721596, 1.        ],
       [0.71428571, 0.52736959, 0.        ],
       [0.        , 0.        , 1.        ],
       [0.85714286, 0.74899021, 0.        ],
       [1.        , 0.70540206, 1.        ]])

In [ ]:
model.save("branchpred.h5")

In [ ]:
caste = ['oc', 'bc-a', 'bc-b', 'bc-c', 'bc-d', 'bc-e', 'sc', 'st']
gender = ['m', 'f']
branch = ['cse', 'ece', 'eee', 'ce', 'me']
inputData = pd.DataFrame(columns=['caste', 'rank', 'gender'])
casteInput = input('Enter the caste :')
rankInput = int(input('Enter the rank :'))
rankInputs=(rankInput-13808)/(94518-13808)
genderInput = input('Enter the gender :')
casteInput = caste.index(casteInput)
casteInputs=(casteInput-0)/7;
genderInput = gender.index(genderInput)

from keras.models import load_model
model = load_model('/content/branchpred.h5')

modelInput = [casteInputs,rankInputs, genderInput]
h=model.predict([modelInput])
labels = ['ce', 'cse', 'ece', 'eee', 'me']
print('branch :',labels[model.predict([modelInput]).argmax(axis=1)[0]])



Enter the caste :oc
Enter the rank :6789
Enter the gender :m
branch : ece
